### ISSUE TITLE
Add Heading components

### ISSUE THREAD

**Issue by dhruvsaxena1998** [kairoverse/kairo-notion-x#4]
## Heading components

Need to create heading components.

![image](https://user-images.githubusercontent.com/14231264/196230359-3e3fce3f-7205-4077-a212-abaf9240faf1.png)

- [x] Heading 1
- [x] Heading 2
- [x] Heading 3

> Formatting Options
- [x] Italic
- [x] underline
- [x] strikethrough
- [x] color
- [x] background color
- [x] code

**Comment by 20RitikSingh** [comment]
can i do this?
